# Generated by Django 5.1.3 on 2025-01-30 13:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_created_at_useraccount_update_ate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.UserProfile.avatar_path),
        ),
    ]
