# Generated by Django 5.1.3 on 2025-02-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
